Samofalov_second_push_request
ITMO-NSS-team/Fedot.Industrial pull request #16
Opened 2022-09-12 15:27 UTC by GishB

1. Some changes in SSTdetector.py (look at _score_offline function) 1.1. small changes according to PEP8
1.2. a small fix to _score_offline function
1.3. add _n_components function (it makes code a bit logical) 1.4.  add some more hyperparametes for SST
2. Some changes in Aleksandt_test.py>> (rename) ReportTestAleksandtEdited.py 2.1 Small changes according to PEP8
2.2 Do analysis with local well-log dataset and make conclusions.

2022-09-12 16:09 UTC, nicl-nno requested changes
Если это полноценное внесение изменений в код - то и название PR-а, и название файлов хотелось бы более семантичные. Интересные факты про TestAlexandr и second_push_request можно при необходимости в описании упомянуть.

2022-09-12 16:09 UTC, nicl-nno commented on cases/anomaly_detection/SSTdetector.py
>                  X_history = self.spectrum_extractor.ts_vector_to_trajectory_matrix(
Пучарм намекает, что нейминг и офорление имеют недостатки:

![image](https://user-images.githubusercontent.com/5711814/189700130-672223b6-1cf0-4e38-bda9-f348b7991f93.png)

2022-09-12 16:09 UTC, nicl-nno commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +        quantile_rate=0.95,n_components=2,view=True,dynamic_mode=False)
В чем тонкая разница между runner и run? Ну и оформление.

2022-09-13 09:10 UTC, v1docq requested changes

2022-09-13 09:10 UTC, v1docq commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +import seaborn as sns
Импорт библиотек можно перенести в начало файла

2022-09-13 09:10 UTC, v1docq commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +                        np.array(dataframe_edited_X['unitless'][500:2500]))
Функции для вызова тоже стоит задавать в начале файла. Имя функции лучше переименовать с runner на run_experiment например

2022-09-13 09:10 UTC, v1docq commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +
Вот это можно добавить как docstring в класс SST

2022-09-13 09:10 UTC, v1docq commented on cases/anomaly_detection/SSTdetector.py
> +    #              ):
Если ты переопредилил конструктор классов то старый можно просто удалить

2022-09-14 10:02 UTC, technocreep commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +    sys.path.append(r"C:\Users\1\Desktop\GitHub\Fedot.Industrial")
корневой путь импортируется вот так:

`from core.operation.utils.utils import PROJECT_PATH`

если, конечно, сделать ребейз на мэйн

2022-09-14 13:11 UTC, closed without merging

2022-09-14 13:14 UTC, nicl-nno commented
Если ты продолжаешь работу над этой задачей - продолжай, пожалуйста, в этом же PR-е, чтобы комментарии не терялись и ты мог отвечать на них тут же.

2022-09-14 13:20 UTC, GishB commented
Хорошо, я просто сейчас PR хочу сделать в Aleksandr_test_case, который для меня сделали изначально. Мое решение не для main ветки.

2022-09-14 13:22 UTC, nicl-nno commented
Но целевую ветку тоже можно менять:

![image](https://user-images.githubusercontent.com/5711814/190165570-33238a16-ea4e-4136-87b5-dd88ba65995a.png)