Alexander test case
ITMO-NSS-team/Fedot.Industrial pull request #18
Opened 2022-09-20 08:05 UTC by v1docq

2022-10-04 12:32 UTC, technocreep requested changes
Привет! Отличная работа, но есть несколько замечаний:

1. Перед Пушем обязательно проверяй код в линтере. Если используешь PyCharm, то он должен подсказывать - постарайся устранить мелкие недочёты вроде недостающих пробелов, именования переменных и методов, лишних строк и т.д.
2. Модуль есть модуль, в нём функционал, кмк. Примеры использования, особенно такие большие лучше вынести в соответствующий раздел
3. Не могу понять, почему возникли конфликты с файлами, которые были в проекте до того, как ты начал работу над своей частью. Перед следующим пушем сделай ребейс на мэйн, возможно мэйн ушёл чуть вперёд, но не кардинально по твоей части.
4. Если пишешь коммент, то лучше писать на английском
5. Нужно подумать над нэймингом модулей, как я уже отметил в одном из замечаний: "зачем нам тестировать Александра"? Имя должно отражать назначение.
6. ReportTestAleksandr - вот этот модуль точно переработай в отдельный туториал и не забудь подтянуть исходные данные, если они нужны

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/Alexandr_test.py
> +        x : 1d numpy array
этого аргумента у метода нет

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/Alexandr_test.py
> +
много пустых строк

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/Alexandr_test.py
> +        proj = np.diag(np.sqrt(w[:2])) @ v.T[:2]
это точно нужно вычислять?

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/Alexandr_test.py
> +            filtred_score = list(map(lambda x: 1 if x > q_95 else 0, score_diff))
иксом также именуется аргумент метода, лучше что-то переименовать

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/SKAB_experiment.py
> +from tsad.evaluating.evaluating import evaluating
Если вводишь новый пакет - обнови `requirements`

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +    def score_offline_2d_average(self, dynamic_mode: bool = True):
применения этому методу я не нашёл. Он ещё и не возвращает ничего

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +        window: list = []
`window: list = []` лучше заменить на `window = list()`

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +            for current_index in range(start_idx, end_idx, step):
вот отсюда у тебя начинается блок кода, который потом пару раз дублируется. Предлагаю заменить его отдельным методом

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +    def _score_offline(self, _x, dynamic_mode=True):
в этом методе тоже есть дублирование кода

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +        out_values = [values[0][0], values[0][1], values[0][2], values[0][7], values[0][8], values[0][9], values[0][10]]
`out_values = np.array([values[0][i] for i in range(11)])`

2022-10-04 12:32 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +    def _generate_features_from_one_ts(self, time_series) -> list:
а в квантильном генераторе нет такого метода?

2022-10-22 18:47 UTC, GishB commented on cases/anomaly_detection/Alexandr_test.py
> +import numpy as np
Тут речь скорее идет об эксперименте обычном на реальных данных - поэтому так модуль и называется

2022-10-22 18:48 UTC, GishB commented on cases/anomaly_detection/Alexandr_test.py
> +# In[4]:
Понял, исправлю в следующем комите с экспериментом

2022-10-22 18:49 UTC, GishB commented on cases/anomaly_detection/Alexandr_test.py
> +        """Change point detection with Singular Spectrum Transformation.
Согласен

2022-10-22 18:49 UTC, GishB commented on cases/anomaly_detection/Alexandr_test.py
> +            x_scaled = MinMaxScaler(feature_range=(1, 2))                            .fit_transform(self.ts.reshape(-1, 1))[:, 0]
Бывает такое, не замечаю. В jupyter их нет, а в PyCharm почему-то появляются

2022-10-22 18:50 UTC, GishB commented on cases/anomaly_detection/Alexandr_test.py
> +#                 score[t - 1] = np.linalg.norm(distance_matrix(X_history.T, X_test.T)\
Для себя оставляю, чтобы возвращаться если что. Однако, учитывая, что PR в main - согласен

2022-10-22 18:51 UTC, GishB commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +import seaborn as sns
Согласен, буду поправлять в будущих комитах

2022-10-22 18:51 UTC, GishB commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +    dataframe_columns = dataframe.columns  # #колонки dataframe
Т.к. комит в main - согласен

2022-10-22 20:32 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +class SingularSpectrumTransformation:
Так и есть - надо бы заново комит кинуть

2022-10-22 21:22 UTC, GishB commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +if __name__ == "__main__":
Ok

2022-10-22 21:35 UTC, closed without merging