Features caching implemented
ITMO-NSS-team/Fedot.Industrial pull request #25
Opened 2022-10-12 12:27 UTC by technocreep

* If `use_cache` bool flag in `Config.yaml` is `True`, then every feature space generated during experiment is cached into cache folder. To do so a hash from function `get_features` arguments and generator attributes is obtained. Then resulting feature space is dumped via pickle library

* also fixed [vulnerability](https://github.com/ITMO-NSS-team/Fedot.Industrial/security/dependabot/1)

2022-10-17 10:25 UTC, v1docq requested changes

2022-10-17 10:25 UTC, v1docq commented on core/TimeSeriesClassifier.py
>          self.predictor_list = PredictorList(train_labels_set=train_tuple[1],
а в чем идея коммита exit()?

2022-10-17 10:25 UTC, v1docq commented on core/api/tsc_API.py
> +                                                         use_cache=self.use_cache)}
Может вместо try except обвязки попробывать assert по имени ключа?

2022-10-17 10:25 UTC, v1docq commented on core/models/ExperimentRunner.py
> +        return hsh
А распиши плиз где нибудь поподробнее в чем идея "хеширования" фичей. Просто в федоте то есть хеширование в ходе композирования для уменьшения времени сходимости. У нас все таки немного другая логика в хешировании.

2022-10-17 10:25 UTC, v1docq commented on core/models/ExperimentRunner.py
> +
Надо подумать будем ли мы дальше развивать историю с хешированием фичей. Если да то стоит вынести наверное в отдельный класс.

2022-10-17 11:27 UTC, technocreep commented on core/models/ExperimentRunner.py
> +        return hsh
тут идея в том, чтобы создать уникальный указатель из имени датасета, подвыборки (тест или трейн) и генератора признаков. Уникально идентифицировать генератор можно в нашем случае лишь используя набор параметров в виде словаря `obj.__dict__`, исключая при этом некоторые динамические атрибуты. Так мы можем отделить `quantile` и `quantile_window` генераторы друг от друга и создать уникальный для каждого случая хэш входящих в метод данных, а затем связать его с выходными данными - набором признаков

2022-10-17 11:30 UTC, technocreep commented on core/TimeSeriesClassifier.py
>          self.predictor_list = PredictorList(train_labels_set=train_tuple[1],
ето косяк

чисто техническая строка

2022-10-17 11:52 UTC, technocreep commented on core/api/tsc_API.py
> +                                                         use_cache=self.use_cache)}
тут мысль в том, что не для всех генераторов в конфете есть заданные параметры. Например, для топологического - нет, но инициализация генератора предполагает наличие словаря с параметрами, пускай даже пустого

не уверен, что с `assert` можно реализовать то же, что и с `try-except`

предлагаю, например, такой вариант: `experiment_dict['feature_generator_params'].get(gen_name, dict())`

2022-10-21 15:07 UTC, v1docq commented on core/api/tsc_API.py
> +                                                         use_cache=self.use_cache)}
Окей давай оставим так

2022-10-21 15:29 UTC, v1docq approved these changes

2022-10-27 11:13 UTC, merged