WSS_algorithm_test
ITMO-NSS-team/Fedot.Industrial pull request #27
Opened 2022-10-17 08:52 UTC by GishB

Minor update for auto window size selection via AC and DFF

> MWF and SuSS dosen`t work

- "Windows Size Selection in Unsupervised Time Series Analytics: A Review and Benchmark. Arik Ermshaus, Patrick Schafer, and Ulf Leser"

2022-10-17 10:07 UTC, v1docq requested changes

2022-10-17 10:07 UTC, v1docq commented on cases/anomaly_detection/WSSAlgorithms.py
> +            list_score_peaks.append(score_list[i])
Тоже самое что и выше замечание

2022-10-17 10:07 UTC, v1docq commented on cases/anomaly_detection/WSSAlgorithms.py
> +            list_stats_diff.append(stats_diff)
огромный пробел появился откуда то

2022-10-17 10:07 UTC, v1docq commented on cases/anomaly_detection/WSSAlgorithms.py
> +        pass
Я так понимаю здесь вылезают ошибки? надо написать тогда тесты для их отладки

2022-10-17 10:07 UTC, v1docq commented on cases/anomaly_detection/WSSAlgorithms.py
> +
Убрать копирование из ноутбука

2022-10-17 10:07 UTC, v1docq commented on cases/anomaly_detection/WSSAlgorithms.py
> +        return window_size_selected, list_score
это можно переписать аккуратно в виде словаря
window_size_selected, list_score  = {'highest_autocorrelation':self.autocorrelation(),
..}

2022-10-17 10:07 UTC, v1docq commented on cases/anomaly_detection/WSSAlgorithms.py
> +    return dataframe_edited_
Вынести в отдельный файл в экспериментом и сделать ноутбук с экспериментом и визуализацией

2022-10-17 10:07 UTC, v1docq commented on cases/anomaly_detection/WSSAlgorithms.py
> +        print(f'{window_size_selected_3} - ЭКГ киберспортсмена за игрой в доту при помощи DFF')
Подробности что это ЭКГ за игрой в доту стоит убрать. Просто ЭКГ спортсмена под нагрузкой

2022-10-17 11:01 UTC, technocreep requested changes
у меня основные замечания такие:

а) в пайчарме есть кнопка внизу - problems. Нажми её, пожалуйста, и пробегись по отмеченным ошибкам
б) поправить докстринги
в) исключить комментарии, не влияющие на понимание кода принципиально и перевести оставшиеся на английский

2022-10-20 21:23 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +            list_score.append(score)
Так как алгоритм имеет сложность o(n), то важно определить window_max и исследовать все возможные варианты окон от window_min до window_max.

p.s. window_min тоже можно ограничить если есть предположения о его размере изначальном

2022-10-20 21:25 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +#!/usr/bin/env python
Не замечаю, это PyCharm делает сам

2022-10-22 17:09 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +    """
Ok

2022-10-22 17:09 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +            'multi_window_finder'. По умолчанию всегда будет 'dominant_fourier_frequency'
Ok

2022-10-22 18:34 UTC, GishB reviewed
Сделал amend commit - должны быть изменения.

Работают все 4 метода: MWF, SuSS, DFF, AC (По методу SuSS и MWF есть вопросы*)
*
1) По методу MWF не понятно как лучше выбирать первый локальный минимум. Строчка - 163
2) По методу SuSS не понятно, что в статье подразумевается под roll_range - предположил, что речь идет о np.var(?). Строчка - 124

2022-10-24 08:58 UTC, technocreep requested changes
Отличная работа! Осталось немного поправить доки

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        time_series: it can be a list or np.array()
с докстрингами ничего не случилось, несмотря на замечания: по-прежнему остались пояснения на русском, например, аргументы конструктора не вынесены в описание класса. Вообще конкретно в этом случае как в описании класса, так и в конструкторе присутствует одна и та же запись `Window size selection class`, из которой не совсем ясно, зачем нужен класс.

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        last_update_#2: 21.10.2022 @GishB
что такое ласт апдейт и нужна ли тут данная информация?

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        """
Это должно выглядеть немного иначе:
```
""" 
Find global max value id for the highest_autocorrelation method.

:param score_list: a list of scores obtained ....
:return: a tuple of window_size_selected and list_score_peaks
"""
```

ПРимерно вот так. Просто потом из этих докстрингов собирается документация и хорошо бы, чтоб всё было в одном стиле

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        list_f = []  # Зачем сохранять этот список? В статье это важно было, но не указано где использовать
раз технически он не нужен, то можно от него избавиться?

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        """
не ясно назначение стрелки от `temp_size` к `selected window size`, надо тут тоже навести порядок

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        stat_w = [[np.mean(ts[i:i+window_size]), np.std(ts[i:i+window_size]), np.var(ts[i:i+window_size])]\
такие комментарии не стоит отправлять в мэйн, поскольку это ты чисто для себя пишешь

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        return window_size_selected, list_score
а зачем нужен этот метод, если он нигде не участвует?

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        return window_size_selected, list_score
к тому же, коль скоро в нём фигурируют атрибуты класса, то может проще в нужный момент написать:
`window_size_selected, list_score = self.dict_methods[self.wss_algorithm]()`
А не создавать отдельный метод ?

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        -------------------------------------------------------------------
дважды THE

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +                      for i in range(self.window_min, self.window_max)]
в нескольких местах у тебя бэкслэш в таких выражениях - он не нужен

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +from scipy.signal import find_peaks, argrelextrema
```
from typing import Union

import numpy as np
from scipy.signal import argrelextrema, find_peaks

```

2022-10-24 08:58 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +            list_score.append(score)
Это я понимаю) 

просто хочу удостовериться, что это нормально, когда интервал исследуемых значений `[min, max)`, а не `[min, max]`. Вдруг на самом деле важно включить максимальное значение

2022-10-24 11:04 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +            self.window_min = 10
ещё такой вопрос назрел: а нельзя ли так же как `window_max` рассчитывать `window_min`? Просто почему именно 10 - дефолтное значение, а не 7 или 5? Возможно, стоит здесь выставить 5% от длины ряда, например

2022-10-24 12:23 UTC, technocreep commented
Ещё во время тестирования на реальном датасете отловил интересную ошибку. Написал небольшой скрипт:

```python
    import numpy as np
    from time import time
    from core.operation.utils.load_data import DataLoader

    methods = ['multi_window_finder', 'summary_statistics_subsequence',
               'dominant_fourier_frequency', 'highest_autocorrelation']

    train, test = DataLoader('Beef').load_data()
    single_ts = np.array(train[0].iloc[1])
    for method in methods:
        try:
            start = time()
            wss = WindowSizeSelection(wss_algorithm=method,
                                      time_series=single_ts,
                                      window_min=len(single_ts) // 10,
                                      window_max=len(single_ts) // 3)

            window_size_selected, list_score = wss.runner_wss()
            elapsed = round(time() - start, 2)
            
            print(f'For {method}. Time elapsed: {elapsed}')
            print("window_size_selected: ", window_size_selected)
        except:
            print(f'For {method} - cannot be calculated')
            continue
```

вылетает следующая ошибка: `ValueError - Operands could not be broadcast together....`

Причём это для всех вариантов окна в заданном интервале

дальше - интереснее. Если я для примера выбираю разные временные ряды из одного датасета (читай, меняю `iloc`), то результаты для разных методов получаются разные:

- для 13-го ряда

```console
For multi_window_finder. Time elapsed: 0.93
window_size_selected:  58
For summary_statistics_subsequence. Time elapsed: 8.8
window_size_selected:  47
For dominant_fourier_frequency. Time elapsed: 0.1
window_size_selected:  47
```
- для 1-го ряда

```console
For multi_window_finder. Time elapsed: 0.92
window_size_selected:  122
For summary_statistics_subsequence. Time elapsed: 7.94
window_size_selected:  47
For dominant_fourier_frequency. Time elapsed: 0.09
window_size_selected:  56
```

Это я к чему. Надо обдумать этот момент и немного переработать алгоритм так, чтобы он принимал весь датасет и внутри определял нечто вроде усреднённого значения оптимального окна

2022-10-25 18:56 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        time_series: it can be a list or np.array()
Согласен, перенесу docstring вверх. 

Над описанием класса надо подумать - согласен.

2022-10-25 18:57 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        last_update_#2: 21.10.2022 @GishB
Веду учет для себя, чтобы понимать когда я последний раз брался за этот код)

2022-10-25 19:03 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +            self.window_min = 10
На самом деле можно выбрать любое значение. В статье предлагалось выбирать несколько % (т.е. 5) или фиксированное значение (скажем 10) - это если о window_min.

Я предполагаю, что для работы алгоритма change point detection лучше выставить изначально стандартное значение window_min порядка 10 это позволит исключить выбор малых окон алгоритмами WSS + 5% в некоторых TS может быть порядка 2000 единиц, что не очень хорошо

2022-10-25 19:31 UTC, nicl-nno commented on cases/anomaly_detection/WSSAlgorithms.py
> +        last_update_#2: 21.10.2022 @GishB
Кажется это лучше отслеживать через локальный git.

2022-10-27 22:50 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +            self.window_min = 10
Возможность кастомизации реализована в классе. Если человек не задаст этого параметра, то он изменится на предлагаемый мною

2022-10-27 22:52 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +                      for i in range(self.window_min, self.window_max)]
Выражение слишком длинное, PyCharm ругается и предлагает редактировать

2022-10-28 00:21 UTC, GishB commented
1) Выложил 2 ноутбука с экспериментом на локальных данных + SKAB с SST + WSS метод highest_autocorrelation
2) Отредактировал WSS согласно замечаниям + немного изменил работу алгоритма в случае если time series пришло маленькое (из-за этого скорее всего могла быть ошибка с Operands could not be broadcast together)
   1) Изменил подход к реализации выбора окна для MWF. Однако, к сожалению, метод все еще нестабилен из-за плохой реализации поиска локальных минимумов.
3) алгоритм SST немного отредактированный под нужны WSS (с учетом замечаний)
p.s. надеюсь ничего не улетело из виду
p.s.s. по поводу нестабильного выбора окна: 1) MWF нестабиленый из-за реализации поиска первого локального минимума. 2) SuSS из-за параметра np.var работает некорректно. 3) DFF - так и должен прыгать это его недостаток. 4) highest_autocorrelation теперь должно работать

2022-10-29 10:28 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        last_update_#2: 21.10.2022 @GishB
Удалил

2022-10-29 10:29 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        time_series: it can be a list or np.array()
Докстринги улетели вверх, русского описания больше нет в классе

2022-10-29 10:30 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        """
Дал описание каждой функции класса по аналогии

2022-10-29 10:30 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        list_f = []  # Зачем сохранять этот список? В статье это важно было, но не указано где использовать
Удалил

2022-10-29 10:31 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        """
Порядок навел. Описание функций класса составлено аналогично везде

2022-10-29 10:31 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        stat_w = [[np.mean(ts[i:i+window_size]), np.std(ts[i:i+window_size]), np.var(ts[i:i+window_size])]\
Комментариев больше нет в commite

2022-10-29 10:31 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        -------------------------------------------------------------------
Исправил

2022-10-29 10:32 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +from scipy.signal import find_peaks, argrelextrema
Исправил - окей. Можно еще раз повторить зачем мы так делаем и на основании какого правила?

2022-10-29 10:37 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +            list_score.append(score)
Это не нормально, но не критично

2022-10-29 10:46 UTC, GishB commented
@technocreep 
https://github.com/ITMO-NSS-team/Fedot.Industrial/pull/28#discussion_r1003088564
>
Исправил, согласен.

if self.lag is None:
    self.lag = round(self.ts_window_length / 2)
Отдельным комитом прилетит с обновлением функции DFF*


https://github.com/ITMO-NSS-team/Fedot.Industrial/pull/28#discussion_r1003078778
> рефакторинг.
Исправил по аналогии - спасибо)
Отдельным комитом прилетит с обновлением функции DFF*

https://github.com/ITMO-NSS-team/Fedot.Industrial/pull/28#discussion_r1003067425
> ReportTestAleksandrEdited.py
Отдельным комитом прилетит с обновлением функции DFF*

2022-10-29 10:49 UTC, GishB commented
https://github.com/ITMO-NSS-team/Fedot.Industrial/pull/27#issuecomment-1288954783
>
Немного изменил работу класса в случае если time series пришло маленькое (из-за этого скорее всего могла быть ошибка с Operands could not be broadcast together)
>
Изменил подход к реализации выбора окна для MWF. Однако, к сожалению, метод все еще нестабилен из-за плохой реализации поиска локальных минимумов.

2022-10-30 20:41 UTC, GishB commented
> Тут только первый эксперимент не представлен
ReportTestAleksandrEdited.py

2022-10-31 09:55 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +from scipy.signal import find_peaks, argrelextrema
легко - это раздел руководства pep8 про [импорты](https://peps.python.org/pep-0008/#imports)

2022-10-31 11:03 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        Calculate metric value based on chosen chosen window size for the highest_autocorrelation method
chosen chosen

2022-10-31 11:03 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +                      for i in range(self.window_min, self.window_max)]
я понимаю, просто цитирую ПЧ
<img width="397" alt="image" src="https://user-images.githubusercontent.com/44948116/198993693-7a05c378-1e4e-4910-8efd-f38c202fcb98.png">

2022-10-31 11:04 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +                      for i in range(self.window_min, self.window_max)]
ну эт не страшно в принципе

2022-10-31 11:47 UTC, technocreep requested changes
классно! отличный прогресс!

Но, помимо обозначенных замечаний, есть ещё один важный момент

Подсмотри в мэйн ветке `requirements.txt`, какие там прописаны библиотеки и обнови это у себя, чтобы потом не было проблем с автоматической сборкой документации

2022-10-31 11:47 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +
the the

2022-10-31 11:47 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        """
ndarray, а не narray

2022-10-31 11:47 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +
прикольная реализация, но я вот о чём подумал. По больше части (процентов 80) временных рядов, [с которыми мы сталкиваемся](http://www.timeseriesclassification.com/dataset.php) - меньше 1000, то есть не попадают в предел, обозначенный в этом условии


получается, есть вероятность, что алгоритм выберет в качестве окна величину == длине временного ряда, смысл оконного метода (спектрального или квантильного) потеряется. Может быть оставить 50%, как считаешь?


иначе, в некоторых случаях, такие методы извлечения признаков, как quantile и window_quantile, или spectral и window_spectral схлопнутся в один

2022-11-08 13:24 UTC, technocreep commented
Пока ты не сделал очередной пуш, добавлю кое-что. Ко всем модулям, где необходимо документирование или оно уже есть, делай, пожалуйста, докстринги в [гугл-стиле](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

2022-11-09 23:24 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +
Можно, конечно, и оставить. Однако, возникают проблемы для подбора гипепараметров если изначально временной ряд был маленьким. 

К примеру, если highest_autocorrelation предложит выбрать параметр окна 11. Следующая задача выбрать какой размер окна у подпоследовательности. 
>> Задачу решить не представляется возможным в данной реализации кода. 

Для решения обозначенной проблемы написал этот скрипт. (updated)
        if  len(time_series) <= 10 and len(time_series) >= 2 :
            self.window_max = len(time_series)
            self.window_min = 2
            

Думаю, что, лучше, будут следующие варианты:
 a)      if int(len(self.time_series)) <= self.window_min:
            window_size_selected, list_score = int(len(self.time_series)), []
            
 б)      Убрать ограничение в коде типа range(self.window_min, self.window_max)
 
  ` list_score = [self.high_ac_metric(self.time_series[i:] + self.time_series[:i], i) \
                      for i in range(self.window_min, self.window_max)]`

2022-11-10 00:33 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        """
Точно

2022-11-10 00:36 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        Calculate metric value based on chosen chosen window size for the highest_autocorrelation method
ok

2022-11-10 00:39 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +    def features_average_(self, temp_average_features):
Честно, уже не помню зачем. Предполагаю, что PyCharm предложил мне заменить повторяющиеся код в тексте на функцию и автоматически определил андерскор.

2022-11-10 00:41 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        filtred_score = list(map(lambda _x: 1 if _x > q_95 else 0, score_diff))
Возможно. Исправил

2022-11-10 00:49 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                score_list.append(np.linalg.norm(distance_matrix(average_features.T, current_features.T), 2))
Интересно получается. Не замечал ранее - с этой частью кода не работал.

2022-11-10 00:56 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                score_list.append(np.linalg.norm(distance_matrix(average_features.T, current_features.T), 2))
Можно. Сделал

2022-11-10 00:57 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                score_list.append(np.linalg.norm(distance_matrix(average_features.T, current_features.T), 2))
Заменил на score_list = list(score_list)

2022-11-10 01:00 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                    _n_components(x_test, x_history, self.trajectory_window_length)
Не совсем - судя по функции там self.trajectory_window_length не нужен

2022-11-10 01:00 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        window lenght of vectors in Hankel matrixes
ok

2022-11-10 01:01 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                 is_scaled=False,
ok

2022-11-10 01:02 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                 is_scaled=False,
Не очень понял, что конкретно здесь плохо - PEP 8 не ругается

2022-11-10 19:18 UTC, GishB commented
> Пока ты не сделал очередной пуш, добавлю кое-что. Ко всем модулям, где необходимо документирование или оно уже есть, делай, пожалуйста, докстринги в [гугл-стиле](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

Сделал, теперь по красоте. Сейчас исправлю проблему с docstring - там что-то странное

2022-11-10 21:44 UTC, GishB commented
Не могу исправить ошибку с docstring.

1. Обновил numpy до версии 1.23.4
2. Версия python > 3.9

2022-11-14 16:13 UTC, technocreep requested changes
Очень круто всё, доки мне особенно понравились, хотя ещё немного осталось добить

2022-11-14 16:13 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +    """
Очень круто сделал доки, молодец! Но есть нюанс: аннотировать типы нужно либо в конструкторе (или методе), либо в докстрингс. Этот момент тоже надо учесть, а именно оставить аннотацию в конструкторе

В [примере](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) смотри на метод `function_with_pep484_type_annotations`

2022-11-14 16:13 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +            score_list = list(self.ts_window_length)
вот тут в 102 строке ты в `list` складываешь тип `int`. Это невозможно, потому что `self.ts_window_length` - не итерируемый объект. Так ведь?

2022-11-14 16:13 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +    def _sst_svd(self, x_test, x_history, n_components):
Тут надо решить: либо ты не документируешь скрытый метод (что, разумеется, не обязательно), либо описываешь его до конца

2022-11-14 16:13 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +            You can chose between:
choose

2022-11-14 16:13 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +        wss_algorithm (str): type of WSS algorithm for your task. By default, it is 'dominant_fourier_frequency'.
тут тоже надо убрать аннотацию типов из доков и оставить в конструкторе

это также касается значений, возвращаемых методами – см. в примере метод `function_with_pep484_type_annotations`

2022-11-17 22:53 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +            You can chose between:
Исправил

2022-11-17 22:57 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +            window_selected_temp (list): selected window size for your time series.
updated

2022-11-17 23:51 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +        wss_algorithm (str): type of WSS algorithm for your task. By default, it is 'dominant_fourier_frequency'.
Сделал

2022-11-19 23:16 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +    """
Исправил

2022-11-20 00:02 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +    def _sst_svd(self, x_test, x_history, n_components):
Исправил

2022-11-20 00:02 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +            score_list = list(self.ts_window_length)
Исправил

2022-11-20 00:57 UTC, GishB commented
Извиняюсь, лишние комиты залил. Не понимаю теперь как сделать commit чтобы отменить изменения.

2022-11-20 10:54 UTC, GishB commented
1. Обновил docstring к SST и WSS модулям.
2. Обновил алгоритм SuSS теперь он имеет сложность O(log(n)) и не привязан к ограничению window_max и window_min

2022-11-21 12:32 UTC, technocreep requested changes
Всё в целом замечательно, но я заметил пару моментов, на которые ты, вероятно, не обратил внимание, когда делал коммит. Обрати, пожалуйста

2022-11-21 12:32 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +            average_features = self.features_average(temp_average_features)  # 1
вот этот кусок смело можно выносить в отдельный метод, чтобы не раздувать `_score_offline_2d_average`. Потому что хоть в динамическом, хоть не в динамическом режиме, алгоритм вычислений один и тот же

2022-11-21 12:32 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +            temp_average_features:
забыл дописать

2022-11-21 12:32 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +    def local_max_search(self, score_list: list) -> [int, list]:
```python
def local_max_search(self, score_list: list) -> Tuple[int, list]:
    ...
```

2022-11-21 12:35 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +            average_features = self.features_average(temp_average_features)  # 1
странно как выделилось. Поясню, о каком куске речь. В методе `_score_offline_2d_average`:
```python
temp_average_features = [[]] * len(x_scaled)
...
average_features = self.features_average(temp_average_features)  # 1
```

2022-11-21 12:39 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +    def summary_statistics_subsequence(self, lbound: int(20), threshold: float(.89)) -> [int, list]:
Я подумал возможно правильно будет здесь оставить начальные значения в функции.

2022-11-21 12:42 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        return filtered_score
- Вернет "расстояния" для каждого индекса в list

Для True: [0,1,0,0,0,0....,0,1]
Для False:[5,15.55,6,2,3,...,8,50]

2022-11-21 12:43 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                 time_series: Union[list, np.array] = None,
Согласен - забыл

2022-11-21 12:44 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                 is_scaled = False,
Что конкретно, я не понял?

2022-11-21 12:45 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        length_ts(int): length of the time_series.
Пропал видимо, ладно)

2022-11-21 12:47 UTC, technocreep commented on cases/anomaly_detection/WSSAlgorithms.py
> +    def summary_statistics_subsequence(self, lbound: int(20), threshold: float(.89)) -> [int, list]:
тогда 
```python
def summary_statistics_subsequence(self, lbound: int = 20, threshold: float = 0.89) -> Tuple[int, list]:
```

2022-11-21 12:49 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +                 is_scaled = False,
ну, аргумент не аннотирован. Чисто для порядка, остальные же имеют аннотацию

2022-11-21 12:52 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        return filtered_score
В классе он есть:             
` view: bool = True`
` self.view = view`

2022-11-21 12:54 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        return filtered_score
Это я для себя сделал - так проще экспериментировать было. Оставил тут возможность работать с разным выводом self.view. По умолчанию работает как обычно.

2022-11-21 12:56 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                 is_scaled = False,
`        is_scaled: if false, min-max scaling will be applied.` строчка 30

2022-11-21 13:10 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +        return filtered_score
тогда зачем тут это условие, если всё равно `view == True`? Просто ради экспериментов, я правильно понял?

2022-11-21 13:12 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +                 is_scaled = False,
ты меня не совсем понял. Я про
```python
def __init__(self,
            ...
             is_scaled: bool = False,
             ...
```

вот тут, в конструкторе

2022-11-21 13:18 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        return filtered_score
Сейчас - да. Интересно посмотреть вывод у метода для случаев разной предобработки временного ряда (для этого пишу view == False при инициализации класса).

p.s. возможно кто-то еще это захочет это увидеть. Эта маленькая модификация не ломает метод.

2022-11-21 13:21 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +        return filtered_score
окей, принято, пусть будет

2022-11-22 15:59 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        return filtered_score
Done

2022-11-22 16:00 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        length_ts(int): length of the time_series.
Появляется в WSS_Algortihm.py - забыл при копировании (артефакт)

2022-11-22 16:01 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +        length_ts(int): length of the time_series.
Done

2022-11-22 17:04 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +                 time_series: Union[list, np.array] = None,
Done

2022-11-22 17:04 UTC, GishB commented on cases/anomaly_detection/WSS_expirement_local_data.ipynb
> +{
Done

2022-11-22 17:04 UTC, GishB commented on cases/anomaly_detection/WSS_expirement_SKAB.ipynb
> +{
Done

2022-11-22 17:06 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +    def local_max_search(self, score_list: list) -> [int, list]:
Done

2022-11-22 17:06 UTC, GishB commented on cases/anomaly_detection/WSSAlgorithms.py
> +    def summary_statistics_subsequence(self, lbound: int(20), threshold: float(.89)) -> [int, list]:
Done

2022-11-22 18:56 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +            temp_average_features:
Done. Нашел еще пропуски

2022-11-22 19:17 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +            average_features = self.features_average(temp_average_features)  # 1
Done

2022-11-22 19:28 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +            average_features = self.features_average(temp_average_features)  # 1
average_features_2d метод появился.

2022-11-22 20:08 UTC, GishB commented
Обновил файлы исходя из предыдущих замечаний. Надеюсь, теперь точно все хорошо)

По поводу функции _get_window_from_ts_complex - не знаю, что она конкретно делает. Оставил ее пока без docstring.

2022-11-23 13:30 UTC, technocreep approved these changes
Бесподобно! 

Не забудь сделать ребейз, прежде чем зальёшь, и схлопнуть все свои кометы в один

2022-11-23 13:35 UTC, merged