Recommit from 20 september.
ITMO-NSS-team/Fedot.Industrial pull request #28
Opened 2022-10-22 21:40 UTC by GishB

Some minor updates in SSTdetector.py and ReportTestAleksandrEdited.py

1. clean commit history
2. edit some comments and logical methods like __name__ if
3. changes in SSTdetector.py according to technocreep commit

2022-10-24 09:30 UTC, technocreep requested changes
всё супер, но нужно немного подправить

2022-10-24 09:30 UTC, technocreep commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +    # #### quantile_rate - коеффициент аномалии
Вот весь этот роскошный (без сарказма) пример работы алгоритма лучше сформировать в ноутбук и вместе с полученными визуализациями залить - вот это будет круто

И пояснения привести на англ

2022-10-24 09:30 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +    lag : int
орфография - length

2022-10-24 09:30 UTC, technocreep commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +from io import StringIO
оставлю пометку тут, хотя она относится к другой части кода. Просто там не могу оставить. 

в ССТ заметил у тебя дублирование кода. 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/44948116/197491285-7575ffd4-8c85-4dcf-bf13-e9328a8a22e3.png">

Это необходимо исправить. Делается очень просто (картинку прикладываю)
<img width="707" alt="image" src="https://user-images.githubusercontent.com/44948116/197491729-566b66a6-61b7-4d94-969a-27f3f2c768e9.png">

2022-10-24 09:30 UTC, technocreep commented on cases/anomaly_detection/SSTdetector.py
> +    lag : int
дальше, опять про то, куда комментарии не дотягиваются, но мне стало интересно
вот в конструкторе пишешь: 
```
if self.lag is None:
            self.lag = self.ts_window_length / 2
```
при этом в доках строго отмечено, что `self.lag` - `int`. Более того, в 145 строке этот атрибут используется в `range()`

собственно, вопрос: не стоит ли гарантировать округление этого атрибута? например:

`self.lag = round(self.lag)`

2022-10-24 09:30 UTC, technocreep commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +from io import StringIO
извиняюсь, что не к тому модулю прикрепил комментарий 😐

2022-10-28 00:24 UTC, GishB commented on cases/anomaly_detection/SSTdetector.py
> +    lag : int
Комит надо бы закрыть - работаю в другом PR

2022-10-28 00:25 UTC, GishB commented on cases/anomaly_detection/ReportTestAleksandrEdited.py
> +    # #### quantile_rate - коеффициент аномалии
Согласен - сделаю

2022-10-29 10:42 UTC, GishB commented
[https://github.com/ITMO-NSS-team/Fedot.Industrial/pull/28#discussion_r1003088564] @technocreep 
>
Исправил, согласен.

if self.lag is None:
    self.lag = round(self.ts_window_length / 2)
Отдельным комитом прилетит с обновлением функции DFF*


[https://github.com/ITMO-NSS-team/Fedot.Industrial/pull/28#discussion_r1003078778](url)
>
Исправил по аналогии - спасибо)
Отдельным комитом прилетит с обновлением функции DFF*

[https://github.com/ITMO-NSS-team/Fedot.Industrial/pull/28#pullrequestreview-1152794995](url)
>
Отдельным комитом прилетит с обновлением функции DFF*

2022-10-30 20:08 UTC, closed without merging