SVDOptimization
ITMO-NSS-team/Fedot.Industrial pull request #32
Opened 2022-10-31 15:44 UTC by N-31V

2022-11-02 12:10 UTC, technocreep requested changes
Отлично проделанная работа! Выглядит всё хорошо. Вот бы ещё затестить оба эксперимента - ошибки, с которыми они у меня падали я в комментах написал, надеюсь это решаемо.

А так, единственная рекомендация пока - добавить документацию

2022-11-02 12:10 UTC, technocreep commented on cases/object_recognition/run_detection_experiment.py
> +import torch
а этот эксперимент упал с ошибкой `FileNotFoundError: [Errno 2] No such file or directory: '/media/n31v/data/datasets/ALET/trainv4.json'
`

2022-11-02 12:10 UTC, technocreep commented on cases/object_recognition/run_detection_experiment.py
> +import torch
просто если это готовый для запуска кейс, все сопутствующие файлы должны быть рядом с модулем, я полагаю

2022-11-02 12:25 UTC, N-31V commented on core/operation/utils/cv_experimenters.py
> +)
видимо автоформатер перенес из-за длинны строки, поправлю.

2022-11-02 12:26 UTC, N-31V commented on cases/object_recognition/run_detection_experiment.py
> +import torch
Файлы запусков экспериментов сделаны для примера, Илья хотел вписать это потом в общий апи индастриала.

2022-11-08 13:21 UTC, technocreep approved these changes
Кажется, все прошлые замечания исправлены. Поэтому с моей стороны вопросов нет, с меня аппрув

Если у Ильи @v1docq есть замечания, то пусть выскажет, а так не вижу препятствий

2022-11-09 11:33 UTC, v1docq approved these changes

2022-11-09 11:35 UTC, merged